global using Shared.DDD;
global using Carrito.Carrito.Models;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using Carrito.Data;
global using Carrito.Carrito.Exceptions;
global using Shared.CQRS;
global using Carrito.Carrito.Dtos;
global using Mapster;
