global using Catalogo;
global using Carrito;
global using Pedido;
global using Carter;
global using Shared.Extensions;
global using Shared.Exceptions.Handler;
global using Serilog;
global using FluentValidation;
global using Shared.Behaviors;